kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-tweetbot
  namespace: tweetbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-tweetbot
    spec:
      containers:
      - name: susi-tweetbot
        image: fossasia/susi_tweetbot:latest-master
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: susi-tweetbot
      restartPolicy: Always
